#!/bin/bash

dir=$(pwd)
user=$(whoami)
hostname=$(hostname)
disk_size=$(df -h | grep '/dev' | awk '{print($2)}')
disk_avail=$(df -h | grep '/dev' | awk '{print($4)}')
mounted_root=$(df -h | grep -w '/' | awk '{print($1)}')
swap_total=$(free -h | grep 'Swap' | awk '{print($2)}')
swap_used=$(free -h | grep 'Swap' | awk '{print($3)}')
swap_free=$(free -h | grep 'Swap' | awk '{print($4)}')


echo -e "\n"
echo -e "The current directory: $dir"
echo -e "The current date: $(date | head -n1 | awk '{print($2)}'), $(date | head -n1 | awk '{print($3)}')"
echo -e "The user logged in is: $user"
echo -e "Hostname: $hostname"
echo -e "\n"

echo "CPU: "
cat /proc/cpuinfo | grep 'model name' | uniq
lscpu | grep 'Architecture'
lscpu | grep 'MHz'
cat /proc/cpuinfo | grep 'cpu cores' | uniq
lscpu | grep 'Thread(s) per core'
echo -e "\n"


echo "RAM: "
cat /proc/meminfo | grep 'MemTotal'
cat /proc/meminfo | grep 'MemFree'
echo -e "\n"


echo "Disk: "
echo "size: $disk_size"
echo "available: $disk_avail"
echo "mounted on /: $mounted_root"
echo "swap total: $swap_total"
echo "swap used: $swap_used"
echo "swap free: $swap_free"
echo -e "\n"


count_interfaces=0
i=1
n=2
speed=$(speedtest| grep 'Download' | awk '{print($2$3)}')
interfaces_file=$(ls /sys/class/net)

for var in $interfaces_file
do
  count_interfaces=$(( count_interfaces + 1 ))
done


while(( i <= $count_interfaces ))
do
  if [[ $(ifconfig -a | head -n$n | tail -n1 | awk '{print($1)}') = "inet" || $(ifconfig -a | head -n$n | tail -n1 | awk '{print($1)}') = "ether" ]]
    then
      if [[ $(ifconfig -a | head -n$n | tail -n1 | awk '{print($1)}') = "ether" ]]
        then echo -n -e "\E[29G"
        echo -n "$(ifconfig -a | head -n$n | tail -n1 | awk '{print($2)}') "
        echo -n -e "\E[49G"
        echo "$speed"
        i=$(( i + 1 ))
      else
        echo -n -e "$i $(ls /sys/class/net | head -n$i | tail -n1 | awk '{print($i)}')"
        echo -n -e "\E[11G"
        echo -n -e "$(ifconfig -a | head -n$n | tail -n1 | awk '{print($2)}') "
        if [[ $(ls /sys/class/net | head -n$i | tail -n1 | awk '{print($i)}') = "lo" ]]
          then echo -n -e "\E[49G"
          echo "$speed"
          i=$(( i + 1 ))
          fi
      fi
  fi
  n=$(( n+1 ))
done

echo "number of network interfaces: $count_interfaces"
