#!/bin/bash

user=$(whoami)
hostname=$(hostname)
disk_size=$(df -h | grep -w '/' | awk '{print($2)}')
disk_avail=$(df -h | grep -w '/' | awk '{print($4)}')
mounted_root=$(df -h | grep -w '/' | awk '{print($1)}')
swap_total=$(free -h | grep 'Подкачка' | awk '{print($2)}')
swap_used=$(free -h | grep 'Подкачка' | awk '{print($3)}')
swap_free=$(free -h | grep 'Подкачка' | awk '{print($4)}')


echo -e "\n"
echo -e "The current date: $(date | head -n1 | awk '{print($2)}'), $(date | head -n1 | awk '{print($3)}')"
echo -e "The user logged in is: $user"
echo -e "Hostname: $hostname"
echo -e "\n"

echo "CPU: "
echo "model name - $(cat /proc/cpuinfo | grep 'model name' | uniq | cut -d":" -f2)"
echo "architecture - $(lscpu | grep 'Архитектура' | awk '{print($2)}')"
echo "CPU MHz - $(lscpu | grep -w 'CPU МГц' | awk '{print($3)}')"
echo "CPU max MHz - $(lscpu | grep -w 'CPU max MHz' | awk '{print($4)}')"
echo "CPU cores - $(lscpu | grep 'Ядер на сокет' | uniq | awk '{print($4)}')"
echo "Thread(s) per core - $(lscpu | grep 'Потоков на ядро' | awk '{print($4)}')"
echo -e "\n"


echo "RAM: "
echo "Mem Total - $(cat /proc/meminfo | grep 'MemTotal' | awk '{print($2)/1024}') Gi"
echo "Mem Free - $(cat /proc/meminfo | grep 'MemFree' | awk '{print($2)/1024}') Gi"
echo -e "\n"


echo "Disk: "
echo "size: $disk_size"
echo "available: $disk_avail"
echo "mounted on /: $mounted_root"
echo "swap total: $swap_total"
echo "swap used: $swap_used"
echo "swap free: $swap_free"
echo -e "\n"


echo -n "Interface name"
echo -n -e "\E[29G"
echo -n "MAC address"
echo -n -e "\E[49G"
echo "Connection speed"

count_interfaces=0
i=1
n=1
interfaces_file=$(ls /sys/class/net)

for var in $interfaces_file
do
  count_interfaces=$(( count_interfaces + 1 ))
done


while(( i <= $count_interfaces ))
do
  if [[ $(ifconfig -a | head -n$n | tail -n1 | awk '{print($3)}') = "mtu" ]]
    then interface_name=$(ls /sys/class/net | head -n$i | tail -n1 | awk '{print($i)}')
    echo -n -e "$i $interface_name"
  fi

  speed=$(sudo ethtool $interface_name | grep 'Speed' | awk '{print($2)}')

  if [[ $(ifconfig -a | head -n$n | tail -n1 | awk '{print($1)}') = "inet" || $(ifconfig -a | head -n$n | tail -n1 | awk '{print($1)}') = "ether" ]]
    then
      if [[ $(ifconfig -a | head -n$n | tail -n1 | awk '{print($1)}') = "ether" ]]
        then echo -n -e "\E[29G"
        echo -n "$(ifconfig -a | head -n$n | tail -n1 | awk '{print($2)}') "
        echo -n -e "\E[49G"
        echo "$speed"
        i=$(( i + 1 ))
      else
        echo -n -e "\E[11G"
        echo -n -e "$(ifconfig -a | head -n$n | tail -n1 | awk '{print($2)}') "
        if [[ $(ls /sys/class/net | head -n$i | tail -n1 | awk '{print($i)}') = "lo" ]]
          then echo -n -e "\E[49G"
          echo "$speed"
          i=$(( i + 1 ))
          fi
      fi
  fi
  n=$(( n+1 ))
done

echo "number of network interfaces: $count_interfaces"
